---
- name: Copy the artifact
  template:
    src: "backend"
    dest: "./"

- name: Extract the artifact
  raw: tar -xvf backend .

- name: install packages
  raw: npm install

- name: stop pm2 if running
  raw: pm2 stop default

- name: start pm2
  raw: pm2 start npm -- start
