---
- name: Copy the artifact
  template:
    src: "/root/project/artifact.tar.gz"
    dest: "./"

- name: Extract the artifact
  raw: tar -xf artifact.tar.gz

- name: install packages
  raw: npm install

- name: stop pm2 if running
  raw: pm2 stop default

- name: start pm2
  raw: pm2 start npm -- start
