---
- name: Copy the artifact
  copy:
    src: "/root/project/artifact.tar.gz"
    dest: "./"

- name: Extract the artifact
  # raw: tar -xf artifact.tar.gz
  unarchive:
    src: artifact.tar.gz
    dest: .
    remote_src: yes

- name: install packages
  raw: npm install

- name: stop pm2 if running
  ignore_errors: yes
  raw: pm2 stop default

- name: start pm2
  raw: pm2 start npm -- start
